language: node_js
node_js:
  - 6
  - 8
  - stable

cache:
  directories:
    - "node_modules"

before_script:
  - npm prune

after_success:
  - npm run semantic-release

branches:
  only:
    - master
